### PR TITLE
remove backup files, add wildcard to gitignore

### PR DESCRIPTION
**Pull request by glibersat**

### CODE REVIEW

**Comment by glibersat** [comment]
Here's a refactor that uses setuptools and trial (twisted component for running tests) for the tests.
Thanks to that, tests are now running properly (some of them fails tho) and we have a better testing framework that matches twisted asynchronous behaviour.

**Comment by alcinnz** [comment]
Thank you for you're work.

The only thing I have to say. is that I use operations/test.py to have some operations I can call in my tests. It's not quite a test case by itself. I'll fix it up when I redo the operations system.

**Comment by glibersat** [comment]
Thx for the merge !

**Comment by alcinnz** [comment]
You're welcome.

**Pull request merged**
